### ISSUE TITLE
New qts release relaxing the typing-extensions requirement

### ISSUE THREAD

**Issue by vxgmichel** [python-qt-tools/qts#27]
It'd be interested to have a qts 0.3 release that includes the following commit:

f2481ffd9bb181226f19b102ee2b6840049a8f59

In particular I'm interested with this change:
```diff
- typing-extensions ~= 3.10
+ typing-extensions >= 3.10
```

Thank you :)

**Comment by altendky** [comment]
Had to manually upload since I didn't get through fixing the ci, but...  https://pypi.org/project/qts/0.3/  Let me know if this works ok.

**Comment by vxgmichel** [comment]
I'm sorry, I didn't realize `qtrio` also has a dependency to `qts~=0.2.0`:
https://github.com/altendky/qtrio/blob/0fbb2d7542824b0d01625e1bc6dc4c6f5c8627ec/setup.cfg#L46

That means that sadly I still can't have `typing-extensions~=4.4` with `qtrio`.

**Comment by altendky** [comment]
At least I already got CI working over in QTrio with 3.10 and 3.11 support.  I'll go ahead and look over the rest of the deps now too.

**Comment by vxgmichel** [comment]
Thanks for your work it's much appreciated :)

**Comment by altendky** [comment]
For the record, updated in https://github.com/altendky/qtrio/pull/280.  I think I'll wait for other deps to update before releasing QTrio and I'm curious to see how dependabot handles it so I think I'll give that a little time to run and see.  If there are other particular dep issues, let me know and I'll try to expedite them today.

**Comment by altendky** [comment]
Meh, dependabot wasn't being quick so released at https://pypi.org/project/qtrio/0.6.0/ via https://github.com/altendky/qtrio/pull/281 and I'll let it sit now.
